# Generated by Django 5.2 on 2025-05-10 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('presenca', 'Registo de Presença'), ('aula', 'Nova Aula'), ('aviso', 'Aviso Geral'), ('outro', 'Outro')], default='aviso', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('formando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data'],
            },
        ),
    ]
