# Generated by Django 5.2 on 2025-05-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao', '0002_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registopresenca',
            name='justificativo',
            field=models.FileField(blank=True, null=True, upload_to='justificativos/%Y/%m/%d/'),
        ),
        migrations.AlterUniqueTogether(
            name='registopresenca',
            unique_together={('formando', 'aula')},
        ),
        migrations.CreateModel(
            name='CodigoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('valido', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao.aula')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
